IF
True()
THEN
RESPONSE #90
CutSceneID(Player1)
SetGlobal("SHEENAPCAREONE","GLOBAL",1) 
CreateVisualEffectObject("SPGENHLA","K#SHEENA")
CreateVisualEffectObject("SPGENHLA",Player1)
SmallWait(5)
ActionOverride(Player1,ApplySpellRES("K#PCCON",Player1))
ActionOverride("K#SHEENA",ApplySpellRES("K#SHECON","K#SHEENA"))
RESPONSE #10
CreateVisualEffectObject("SPFDEATH","K#SHEENA")
ActionOverride("K#SHEENA",ApplySpellRES("K#KILLS","K#SHEENA"))
END